import type { Metadata } from "next";import { content,type Locale } from "@/content/localized";import { isLocale,localizedMetadata } from "@/lib/localized";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;if(!isLocale(locale))return{};const c=content[locale].legal;return localizedMetadata(locale,"/changelog",`${c.changelogTitle} | Codes by Erax`,c.changelogDescription);}
export default async function Page({params}:{params:Promise<{locale:string}>}){const{locale:raw}=await params;const locale=raw as Locale;const c=content[locale].legal;const groups: [string,string[]][]=locale==="pt"?[
["Recursos disponíveis",["Cadastro e organização de estudantes","Organização por turmas","Perfil individual do estudante","Registro de conversas e acompanhamentos","Tutoria individual e coletiva","Acompanhamento de frequência","Informações acadêmicas e evolução das médias","Histórico de registros","Lixeira para itens removidos","Funcionamento local"]],
["Melhorias desta etapa",["Organização das principais áreas","Centralização dos registros de tutoria","Separação entre acompanhamento individual e coletivo","Ampliação do perfil do estudante","Estrutura acadêmica e de frequência"]],
["Problemas conhecidos",["Alguns itens da lixeira podem não apresentar identificação clara","A persistência dos itens da lixeira precisa ser reforçada","O primeiro acesso precisa de orientações mais claras","Não há sincronização automática entre computadores","Não há aplicativo para celular"]],
["Próximas melhorias em análise",["Tutorial inicial integrado","Identificação mais clara na lixeira","Correções de persistência","Explicações mais simples no primeiro uso","Melhorias de acessibilidade","Expansão das opções de backup"]]
]:[
["Available features",["Student creation and organization","Class organization","Individual student profiles","Conversation and follow-up records","Individual and group tutoring","Attendance tracking","Academic information and average progress","Record history","Trash for removed items","Local operation"]],
["Improvements in this stage",["Organization of main areas","Centralization of tutoring records","Separation of individual and group follow-up","Expanded student profile","Academic and attendance structure"]],
["Known issues",["Some trash items may not display clear identification","Trash persistence needs strengthening","First-time users need clearer guidance","No automatic synchronization between computers","No mobile application"]],
["Improvements under consideration",["Integrated onboarding tutorial","Clearer trash identification","Record persistence corrections","Simpler first-use explanations","Accessibility improvements","Expanded backup options"]]
];return <div className="document page-container"><header><p className="eyebrow">Vínculo Tutoria</p><h1>{c.changelogTitle}</h1><p className="lead">{locale==="pt"?"A documentação pública começa na versão 1.4.0. Versões anteriores não serão apresentadas sem informações verificadas.":"Public history begins with version 1.4.0. Previous versions will not be listed without verified information."}</p></header><section><div className="version-heading"><h2>{locale==="pt"?"Versão":"Version"} 1.4.0</h2><span>{locale==="pt"?"versão atual":"current version"}</span></div>{groups.map(g=><div key={g[0]}><h3>{g[0]}</h3><ul>{g[1].map(i=><li key={i}>{i}</li>)}</ul></div>)}<aside className="notice"><h3>{locale==="pt"?"Observação":"Note"}</h3><p>{locale==="pt"?"As melhorias em análise não representam promessa de data ou garantia de implementação.":"Improvements under consideration do not represent a release-date promise or guarantee."}</p></aside></section></div>}
