import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/seo/JsonLd";
import { content, localeCodes, type Locale } from "@/content/localized";
import { isLocale, localizedMetadata } from "@/lib/localized";
import { siteConfig } from "@/content/site";

export function generateStaticParams(){return localeCodes.flatMap(locale=>content[locale].articles.map(({slug})=>({locale,slug})));}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const {locale:raw,slug}=await params;if(!isLocale(raw))return{};const a=content[raw].articles.find(x=>x.slug===slug);if(!a)return{};return localizedMetadata(raw,`/blog/${slug}`,`${a.title} | Codes by Erax`,a.description,`/blog/${a.alternateSlug}`);}
export default async function ArticlePage({params}:{params:Promise<{locale:string;slug:string}>}){const {locale:raw,slug}=await params;if(!isLocale(raw))notFound();const locale=raw as Locale;const a=content[locale].articles.find(x=>x.slug===slug);if(!a)notFound();return <><article className="article page-container"><Link className="back-link" href={`/${locale}/blog`}>← {locale==="pt"?"Voltar ao blog":"Back to blog"}</Link><header><p className="eyebrow">{locale==="pt"?"Tutoria escolar":"School tutoring"}</p><h1>{a.title}</h1><p className="lead">{a.intro}</p><p className="article-meta"><time dateTime={a.published}>{locale==="pt"?"Publicado em 29 de julho de 2026":"Published July 29, 2026"}</time> · {a.readingTime} · Codes by Erax</p></header>{a.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.items&&<ul>{s.items.map(i=><li key={i}>{i}</li>)}</ul>}</section>)}<aside className="article-cta"><h2>{locale==="pt"?"Organize a continuidade da tutoria":"Organize continuous tutoring"}</h2><p>{locale==="pt"?"Conheça o Vínculo Tutoria e reúna seus principais registros em um único ambiente.":"Discover Vínculo Tutoria and bring essential records into one environment."}</p><Link className="button" href={`/${locale}/vinculo-tutoria`}>{locale==="pt"?"Conhecer o Vínculo":"Discover Vínculo"}</Link></aside></article><JsonLd data={{"@context":"https://schema.org","@type":"BlogPosting",headline:a.title,description:a.description,datePublished:a.published,dateModified:a.modified,inLanguage:locale==="pt"?"pt-BR":"en",author:{"@type":"Organization",name:"Codes by Erax",url:siteConfig.url},publisher:{"@type":"Organization",name:"Codes by Erax"},mainEntityOfPage:`${siteConfig.url}/${locale}/blog/${a.slug}`}}/></>}
