"use client";
import { useState } from "react";
import type { Locale } from "@/content/localized";

const copy = {
  pt: {name:"Seu nome",email:"E-mail para contato",company:"Empresa ou projeto (opcional)",service:"O que você precisa?",services:["Mockup de UI/UX","Site","Aplicativo","Ainda não tenho certeza"],budget:"Faixa de investimento",budgets:["Até R$ 2.000","R$ 2.000 a R$ 5.000","R$ 5.000 a R$ 10.000","Acima de R$ 10.000","Prefiro conversar"],deadline:"Quando gostaria de começar?",deadlines:["Assim que possível","Em até 1 mês","Em 1 a 3 meses","Ainda estou planejando"],details:"Conte um pouco sobre a ideia",help:"Objetivo, público, funcionalidades e referências ajudam a preparar uma proposta mais precisa.",submit:"Solicitar orçamento",sending:"Enviando…",success:"Recebi seu pedido. Em breve entrarei em contato para entender os próximos passos.",error:"Não foi possível enviar agora. Tente novamente em alguns instantes.",choose:"Selecione uma opção"},
  en: {name:"Your name",email:"Contact email",company:"Company or project (optional)",service:"What do you need?",services:["UI/UX mockup","Website","Application","I’m not sure yet"],budget:"Investment range",budgets:["Up to US$ 500","US$ 500–1,000","US$ 1,000–2,000","Above US$ 2,000","I’d rather discuss it"],deadline:"When would you like to start?",deadlines:["As soon as possible","Within a month","In 1–3 months","I’m still planning"],details:"Tell me a little about your idea",help:"Goals, audience, features and references help me prepare a more accurate proposal.",submit:"Request a quote",sending:"Sending…",success:"I’ve received your request. I’ll get in touch soon to discuss the next steps.",error:"It could not be sent right now. Please try again shortly.",choose:"Select an option"},
} as const;

export function QuoteForm({locale}:{locale:Locale}) {
  const c=copy[locale]; const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));if(String(data.website||""))return setStatus("success");const subject=`${locale==="pt"?"Orçamento":"Quote"}: ${data.service}`;const message=[`${c.company}: ${data.company||"—"}`,`${c.service}: ${data.service}`,`${c.budget}: ${data.budget}`,`${c.deadline}: ${data.deadline}`,"",String(data.details)].join("\n");try{const response=await fetch("https://api.web3forms.com/submit",{method:"POST",headers:{"content-type":"application/json","accept":"application/json"},body:JSON.stringify({access_key:"b0d2e2f1-cd72-4e27-a1b2-5cff2018a290",name:data.name,email:data.email,subject,message,from_name:"Codes by Erax — Orçamentos",botcheck:""})});const result=await response.json() as {success?:boolean};if(!response.ok||!result.success)throw new Error();form.reset();setStatus("success");}catch{setStatus("error");}}
  const select=(name:string,label:string,options:readonly string[])=><label>{label}<select name={name} required defaultValue=""><option value="" disabled>{c.choose}</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>;
  return <form className="feedback-form quote-form" onSubmit={submit}><div className="quote-form-grid"><label>{c.name}<input name="name" autoComplete="name" required minLength={2} maxLength={80}/></label><label>{c.email}<input name="email" type="email" autoComplete="email" required maxLength={254}/></label></div><label>{c.company}<input name="company" autoComplete="organization" maxLength={120}/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><div className="quote-form-grid">{select("service",c.service,c.services)}{select("budget",c.budget,c.budgets)}</div>{select("deadline",c.deadline,c.deadlines)}<label>{c.details}<span>{c.help}</span><textarea name="details" rows={7} required minLength={10} maxLength={1500}/></label><button className="button" disabled={status==="sending"}>{status==="sending"?c.sending:c.submit}</button><div role="status" aria-live="polite">{status==="success"&&<p className="success">{c.success}</p>}{status==="error"&&<p className="error">{c.error}</p>}</div></form>;
}
